baseURL = "https://arjunkrishnak.github.io/"
languageCode = "en-us"
title = "Arjun Krishna"
theme = "hugo-resume"

[params]
    firstName = "Arjun"
    lastName = "Krishna"
    address = "San Francisco, California, USA"
    phone = "+16508805337"
    contactNote = "Software Engineer 2 Amazon | Ex-Adobe | IIT Roorkee `19"
    profileImage = "img/profile_pic.jpg"
    email = "arjunkrishna.office@gmail.com"
    
    description = "I am an IIT Roorkee alumnus currently working at Amazon. I'm passionate about machine learning and cloud development. Through my projects and 5+ years of software work experience, I was able to familiarize myself how to design and implement scalable distributed cloud solutions. I am also experienced with building multithreaded performant software workflows in production with latencies in order of milliseconds. I am also familiar with SOLID design principles, data structures, system design and test-driven CI/CD development to provide end to end solutions."
    favicon = "/favicon.ico"
    # what sections
    showDownloadResumeLink = true
    showSkills = true
    showProjects = true
    showAchievements = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true
    showQr = false

[[params.handles]]
    name = "Facebook"
    link = "https://www.facebook.com/arjun.krishna.50309277"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/arjun-krishna-k/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/ArjunKrishnak"

[params.google.analytics]
    trackerID = "UA-152088779-1"
