baseURL = "https://arjunkrishnak.github.io/"
languageCode = "en-us"
title = "Arjun Krishna"
theme = "hugo-resume"

[params]
    firstName = "Arjun"
    lastName = "Krishna"
    address = "Whitefield, Bengaluru"
    phone = "+91 8848661970"
    contactNote = "Software Engineer at Adobe Bengaluru"
    profileImage = "img/profile_pic.jpg"
    email = "arjunkrishna.office@gmail.com"
    description = "I am an IIT Roorkee alumnus currently working at Adobe. I'm passionate about machine learning and data analysis and applying the same to web, mobile and desktop software. Through myprojects and work experience, I was able to familiarize myself with how to handle big data and draw inferences from it. I am also familiar with SOLID design principles and test-driven development to provide end to end solutions. I would love to work with companies working on challenging products and ideas."
    favicon = "/favicon.ico"
    # what sections
    showDownloadResumeLink = true
    showSkills = true
    showProjects = true
    showAchievements = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true
    showQr = false

[[params.handles]]
    name = "Facebook"
    link = "https://www.facebook.com/arjun.krishna.50309277"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/arjun-krishna-k/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/ArjunKrishnak"

[params.google.analytics]
    trackerID = "UA-152088779-1"
