baseURL = "https://arjunkrishnak.github.io/"
languageCode = "en-us"
title = "Arjun Krishna"
theme = "hugo-resume"

[params]
    firstName = "Arjun"
    lastName = "Krishna"
    address = "San Francisco, California, USA"
    phone = "+16508805337"
    contactNote = "Software Development Engineer at AWS AI/ML | Ex-Adobe | IIT Roorkee 2019"
    profileImage = "img/profile_pic.jpg"
    email = "arjunkrishna.office@gmail.com"
    
    description = "Rich 5+ years of software work experience with domain expertise in machine learning, cloud infrastructure systems for machine learning, system design, algorithm design, distributed cloud computing, storage scalability. Demonstrated experience in technical leadership, establishing technical standards and best practices."
    favicon = "/favicon.ico"
    # what sections
    showDownloadResumeLink = true
    showSkills = true
    showProjects = true
    showAchievements = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true
    showQr = false

[[params.handles]]
    name = "Facebook"
    link = "https://www.facebook.com/arjun.krishna.50309277"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/arjun-krishna-k/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/ArjunKrishnak"

[params.google.analytics]
    trackerID = "UA-152088779-1"
